- hosts: all
  become: True
  tasks:
    - name: Create a Docker network for the application
      docker_network:
        name: app-tier
        driver: bridge

    - name: Install Kafka using Docker
      docker_container:
        name: kafka
        image: bitnami/kafka:latest
        state: started
        restart_policy: always
        networks:
          - name: app-tier
        env:
          KAFKA_CFG_NODE_ID: "0"
          KAFKA_CFG_PROCESS_ROLES: "controller,broker"
          KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
        ports:
          - "9092:9092"